steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gcp3-frontend, .]

  - name: gcr.io/cloud-builders/docker
    args: [push, us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gcp3-frontend]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - gcp3-frontend
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gcp3-frontend
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --max-instances=5
      - --set-env-vars=BACKEND_URL=$$BACKEND_URL,NEXT_PUBLIC_APP_URL=$$FRONTEND_URL
    secretEnv:
      - BACKEND_URL
      - FRONTEND_URL

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/gcp3-backend-url/versions/latest
      env: BACKEND_URL
    - versionName: projects/$PROJECT_ID/secrets/gcp3-frontend-url/versions/latest
      env: FRONTEND_URL

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/gcp3-frontend
