"use client";

interface BlogReviewData {
  date: string;
  blog_title: string;
  blog_theme_id: string;
  suggestions: string;
  focus_areas: string[];
}

export function BlogReview({ data }: { data: BlogReviewData }) {
  return (
    <div className="space-y-5">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-white">Blog Review & Suggestions</h1>
        <p className="text-sm text-gray-500 mt-0.5">
          Editorial feedback for "{data.blog_title}" · {data.blog_theme_id} · {data.date}
        </p>
      </div>

      {/* Focus areas reference */}
      <div className="p-4 rounded-xl border border-blue-800/40 bg-blue-950/10">
        <h3 className="text-xs font-semibold text-blue-400 uppercase tracking-wide mb-3">
          Review Focus Areas
        </h3>
        <ul className="space-y-2">
          {data.focus_areas.map((area) => (
            <li key={area} className="text-sm text-gray-300">
              <span className="text-blue-400">•</span> {area}
            </li>
          ))}
        </ul>
      </div>

      {/* Suggestions */}
      <div className="p-6 rounded-xl border border-gray-700 bg-gray-900/40">
        <div className="text-xs font-semibold text-amber-400 uppercase tracking-wide mb-4">
          Gemini Editorial Feedback
        </div>
        <div className="prose prose-invert max-w-none">
          {data.suggestions.split("\n\n").map((para, i) => {
            // Check if this is a numbered suggestion or impact marker
            if (/^\d+\.|HIGH|MEDIUM|LOW|\[/.test(para.trim())) {
              return (
                <div
                  key={i}
                  className="text-gray-200 leading-relaxed text-sm mb-3 p-2 rounded border border-gray-800 bg-gray-900/30 last:mb-0"
                >
                  {para}
                </div>
              );
            }
            return (
              <p key={i} className="text-gray-200 leading-relaxed text-sm mb-3 last:mb-0">
                {para}
              </p>
            );
          })}
        </div>
      </div>

      {/* Source note */}
      <div className="flex gap-2 text-xs text-gray-600">
        <span>🤖</span>
        <span>Review generated by Gemini 2.0 Flash based on today's blog post and market snapshot.</span>
      </div>
    </div>
  );
}
